# See https://pre-commit.com for more information
default_language_version:
  python: python3
fail_fast: false

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        args: [tests]

      - id: editorconfig-checker
        name: editorconfig-checker
        entry: ec
        language: system
        types: [text]
